apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
    template:
      metadata:
        labels:
          app: db
      spec:
        containers:
          - name: mysql
            image: eyja1994/db_sncf:1
            ports:
              - containerPort: 3306
            env:
              - name: MYSQL_ROOT_PASSWORD
                value: "root"

---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: httpdserver
  labels:
    app: httpdserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpdserver
  template:
    metadata:
      labels:
        app: httpdserver
    spec:
      containers:
        - name: httpdserver
          image: eyja1994/server_sncf:1
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql-service
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
