apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: httpdserver
spec:
  type: NodePort
  selector:
    app: httpdserver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
