FROM mariadb
COPY ./script/gare.txt /tmp/dataset/
COPY ./script/ville.txt /tmp/dataset/
COPY ./script/tgv.txt /tmp/dataset/
COPY ./script/create.sql /docker-entrypoint-initdb.d/
COPY ./script/insert.sql /docker-entrypoint-initdb.d/

