---
- hosts: devserver
  vars:
    http_port: 80
  remote_user: root
  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
  - name: ensure php is at the latest version
    yum:
      name: php
      state: latest
  - name: ensure mariadb is at the latest version
    yum:
      name: mariadb-server
      state: latest
  - name: MySQL-python
    yum:
      name: MySQL-python
      state: latest
    notify:
    - start mariadb
  - name: Copy database dump file to remote host
    copy:
      src: /DB/sncf.sql
      dest: /tmp/dataset
  - name: script sncf.sql
    mysql_db:
      name: all
      state: import
      target: /tmp/dataset/sncf.sql
  - name: execute commands
    shell:
      cmd: cd /var/www/html && git clone -b dev --single-branch  https://github.com/Eyja-1994/TP_SNCF.git
    notify:
    - restart httpd
    - restart mariadb

  handlers:
    - name: start mariadb
      service:
        name: mariadb
        state: started
    - name: restart httpd
      service:
        name: httpd
        state: restarted
    - name: restart mariadb
      service:
        name: mariadb
        state: restarted
